version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finsimco
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finsimco
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/Users/jacktran/Documents/backend-assignments/finsimco/postgres_data

  adminer:
    image: adminer
    container_name: simulation_adminer
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data: 