version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finsimco
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finsimco
    ports:
      - 5444:5432
    volumes:
      - postgres_data:/Documents/backend-assignments/postgres_data

  adminer:
    image: adminer
    container_name: finsimco_adminer
    ports:
      - 8082:8080

volumes:
  postgres_data: 